### ISSUE TITLE
T2 8-Piece Mage Boni has a lot of buggy interactions

### ISSUE THREAD

**Issue by Flex13** [Duskhaven/Bug-Reports#1103]
Doesnt work with the following spells: Glacial spike, frostfire bolt. And is wasting the proc if it procs while u are casting a frostbolt. 
This means that you cant throw an instant frostbolt after hardcasting one while it procs. Just useless proc in this case...

Cant really show proof of it without uploading a video but im sure you understand what i mean if you test it. :)

Greetings

**Comment by Flex13** [comment]
Same problem with fire spec. you basically have to cancel your current spell to throw an instant pyroblast. Otherwise the proc will disappear without doing anything...

**Comment by elkdarkshire** [comment]
Same for Arcane,

Netherwind Focus doesnt proc at all from Arcane Missiles...

**Comment by Duskhaven** [comment]
Fixed

**Comment by Flex13** [comment]
thank you :) But Glacial Spike still doesnt work.

**Comment by elkdarkshire** [comment]
because fixes/updates are rolled out on wednesday I assume

arcane missiles still doesnt proc netherwind focus

**Comment by Chromie-the-gnome** [comment]
not really, fixes can be done with a simple restart, reopening isnt a bad idea until noxx gives info if it needs a reset or not.

**Comment by elkdarkshire** [comment]
how does one reopen xD? create anew?
