### ISSUE TITLE
Glyph Chasing Quest

### ISSUE THREAD

**Issue by Blackbird102** [Duskhaven/Bug-Reports#1637]
relates to  #697

quest is buggy again.

Hive'Regal is working, but the other 2 rubbings can't be obtained.

Quest text seems to be wrong as well only showing 2 of the rubbings as objectives

![grafik](https://github.com/Duskhaven/Bug-Reports/assets/56515187/aa063b79-a491-41c7-ae4d-8e2be8f40354)

**Comment by Wheemix** [comment]
Can confirm, standing in front of the Ashi crystal but its not giving me anything if i click to use. Regal worked.

**Comment by Duskhaven** [comment]
Fixed

**Comment by ihugyourmom** [comment]
Not fixed for me. after relog quest shows as complete, but i cant turn it in.
![image](https://github.com/Duskhaven/Bug-Reports/assets/41385353/4967b5fa-b31e-42b8-8faa-3dbd8d805d73)
