### ISSUE TITLE
Demon hunter sets

### ISSUE THREAD

**Issue by BloodGH** [Duskhaven/Bug-Reports#541]
4 piece T1 doesnt seem to work for the aoe on blade dance or the hp regen while in tank stance.
3 piece T2 doesnt work either even though it has the same set bonus as 2 piece T1 which works fine. 
Also all of the energy increase set bonuses dont work either.

**Comment by Duskhaven** [comment]
Fixed.

**Comment by BloodGH** [comment]
t1 aoe on blade dance seems to work 
but the heal still didnt seem like it was working
t2 still doesnt seem to work
